name: Proxies

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-and-combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify Node.js version if needed

      - name: Install Dependencies
        run: npm install node-fetch@2 fs # node-fetch v2 is compatible with CommonJS

      - name: Run Script
        run: |
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const fileUrls = [
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/http.txt',
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/https.txt',
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/socks4.txt',
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/socks5.txt'
          ];

          async function fetchFileContent(url) {
              try {
                  const response = await fetch(url);
                  if (!response.ok) throw new Error(`Failed to fetch file: ${url}`);
                  return await response.text();
              } catch (error) {
                  console.error(error);
                  return '';
              }
          }

          async function combineFiles() {
              let combinedContent = '';

              for (const url of fileUrls) {
                  const content = await fetchFileContent(url);
                  combinedContent += content + '\n\n';
              }

              fs.writeFileSync('active_proxies.txt', combinedContent);
              console.log('File successfully combined into active_proxies.txt');
          }

          combineFiles();
          EOF

      - name: Upload combined file
        uses: actions/upload-artifact@v3
        with:
          name: active_proxies
          path: active_proxies.txt
